import Foundation
import JSONSchemaCodegenCore

@main
struct OpenAPIGenerate {
  static func main() {
    do {
      guard CommandLine.arguments.count == 2 else {
        throw ExampleError("Usage: openapi-generate <openapi.json>; generated Swift is written to stdout.")
      }
      let url = URL(fileURLWithPath: CommandLine.arguments[1]).standardizedFileURL
      let document = SchemaDocument(
        source: try String(contentsOf: url, encoding: .utf8),
        retrievalURI: url
      )
      let components = try OpenAPISchemaGenerator().generateComponents(in: document)
      let namespaces = try components.map { component in
        guard component.name.range(
          of: #"^[A-Za-z_][A-Za-z0-9_]*$"#, options: .regularExpression
        ) != nil else {
          throw ExampleError("This example requires ASCII Swift identifier component names: \(component.name)")
        }
        return """
          public enum \(component.name)Schema {
          \(component.schema.declarations.map { indent($0, by: 2) }.joined(separator: "\n"))
            public static var schema: some JSONSchemaComponent<\(component.schema.outputType)> {
          \(indent(component.schema.expression, by: 4))
            }
          }
          """
      }
      print(
        """
        // Generated by the OpenAPI components example. Do not edit.
        import JSONSchema
        import JSONSchemaBuilder

        \(namespaces.joined(separator: "\n\n"))
        """
      )
    } catch {
      FileHandle.standardError.write(Data("openapi-generate: \(error)\n".utf8))
      exit(1)
    }
  }

  private static func indent(_ source: String, by spaces: Int) -> String {
    source.split(separator: "\n", omittingEmptySubsequences: false)
      .map { $0.isEmpty ? "" : String(repeating: " ", count: spaces) + $0 }
      .joined(separator: "\n")
  }
}

private struct ExampleError: Error, CustomStringConvertible {
  let description: String

  init(_ description: String) {
    self.description = description
  }
}
