import Foundation
import JSONSchemaCodegenCore

@main
struct JSONSchemaCodegenCLI {
  static func main() {
    do {
      guard let options = try Options(arguments: Array(CommandLine.arguments.dropFirst())) else {
        print(Options.help)
        return
      }
      try generate(options)
    } catch {
      FileHandle.standardError.write(Data("error: \(error)\n".utf8))
      exit(EXIT_FAILURE)
    }
  }

  private static func generate(_ options: Options) throws {
    let inputs = options.inputs.sorted { $0.path < $1.path }
    var names: [String: URL] = [:]
    let plans: [(input: URL, typeName: String, output: URL)] = try inputs.map { input in
      let typeName: String
      do {
        typeName = try SchemaFileNaming.typeName(for: input)
      } catch {
        throw CLIError(message: "\(input.path): \(error)")
      }
      let outputName = SchemaFileNaming.outputName(for: typeName)
      let collisionKey = outputName.lowercased()
      if let previous = names[collisionKey] {
        throw CLIError(
          message: "\(input.path): Generated filename '\(outputName)' collides with \(previous.path). Rename one of the input files."
        )
      }
      names[collisionKey] = input
      return (input, typeName, options.outputDirectory.appendingPathComponent(outputName))
    }

    // Plan the complete batch before creating the directory or changing any generated files.
    let documents: [SchemaDocument] = try plans.map { plan in
      do {
        let source = try String(contentsOf: plan.input, encoding: .utf8)
        return SchemaDocument(source: source, retrievalURI: plan.input)
      } catch {
        throw CLIError(message: "\(plan.input.path): #: \(error)")
      }
    }

    let generatedSchemas = try SchemaGenerator().generate(documents)

    let outputs: [(url: URL, data: Data)] = zip(plans, generatedSchemas).map { plan, generated in
      let expression = generated.expression
        .split(separator: "\n", omittingEmptySubsequences: false)
        .map { $0.isEmpty ? "" : "    \($0)" }
        .joined(separator: "\n")
      let source = """
        // Generated by json-schema-codegen. Do not edit.
        import JSONSchema
        import JSONSchemaBuilder

        public enum \(plan.typeName) {
        \(generated.declarations.map { declaration in
          declaration.split(separator: "\n", omittingEmptySubsequences: false)
            .map { "  " + $0 }.joined(separator: "\n")
        }.joined(separator: "\n"))
          public static var schema: some JSONSchemaComponent<\(generated.outputType)> {
        \(expression)
          }
        }

        """
      return (plan.output, Data(source.utf8))
    }

    try FileManager.default.createDirectory(
      at: options.outputDirectory, withIntermediateDirectories: true
    )
    for output in outputs {
      if FileManager.default.fileExists(atPath: output.url.path) {
        let existing = try Data(contentsOf: output.url)
        if existing == output.data { continue }
      }
      do {
        try output.data.write(to: output.url, options: .atomic)
      } catch {
        throw CLIError(message: "\(output.url.path): \(error)")
      }
    }
  }
}

private struct Options {
  let outputDirectory: URL
  let inputs: [URL]

  static let help = """
    USAGE: json-schema-codegen --output-directory <directory> [--] <file.schema.json> ...

    Generate typed JSONSchemaBuilder components from JSON Schema files.

    OPTIONS:
      --output-directory <directory>  Directory for generated Swift files (required).
      -h, --help                      Show this help message.
      --                              Treat all remaining arguments as input paths.

    Each input becomes <PascalCaseBasename>Schema.generated.swift containing a
    public enum and a static schema property. Basenames must start with an ASCII
    letter; use letters, digits, and single '-' or '_' word separators.
    Inputs are sorted, conflicting generated names are rejected, and unchanged
    files are not rewritten.
    """

  init?(arguments: [String]) throws {
    var outputPath: String?
    var inputPaths: [String] = []
    var positionalOnly = false
    var index = 0
    while index < arguments.count {
      let argument = arguments[index]
      if !positionalOnly {
        switch argument {
        case "-h", "--help":
          return nil
        case "--":
          positionalOnly = true
          index += 1
          continue
        case "--output-directory":
          guard outputPath == nil else {
            throw CLIError(message: "'--output-directory' may only be supplied once.")
          }
          index += 1
          guard index < arguments.count, !arguments[index].isEmpty,
            !arguments[index].hasPrefix("-")
          else {
            throw CLIError(message: "'--output-directory' requires a directory path.")
          }
          outputPath = arguments[index]
          index += 1
          continue
        default:
          if argument.hasPrefix("-") {
            throw CLIError(message: "Unknown option '\(argument)'. Use '--help' for usage.")
          }
        }
      }
      inputPaths.append(argument)
      index += 1
    }
    guard let outputPath else {
      throw CLIError(message: "Missing '--output-directory <directory>'. Use '--help' for usage.")
    }
    guard !inputPaths.isEmpty else {
      throw CLIError(message: "At least one '.schema.json' input is required. Use '--help' for usage.")
    }
    outputDirectory = URL(fileURLWithPath: outputPath, isDirectory: true).standardizedFileURL
    inputs = inputPaths.map { URL(fileURLWithPath: $0).standardizedFileURL }
  }
}

private struct CLIError: Error, CustomStringConvertible {
  let message: String
  var description: String { message }
}
